caten_music/models/base.py
# models/base.py

import os

from flask import Flask, current_app
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

config = os.environ.get("APP_SETTING")

if config == "Development":
    print("Development")
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL_FOR_DEVELOPMENT")

elif config == "Testing":
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL_FOR_TESTING")

elif config == "Production":
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL")
    

db = SQLAlchemy(app)

caten_music/routes/login.py
# routes/login.py

from flask import Blueprint, render_template, abort, jsonify, request, redirect, url_for, flash
from jinja2 import TemplateNotFound
from flask_login import login_user, current_user

import datetime

from caten_music import helper


login_bp = Blueprint("login_bp", __name__,
                    template_folder='templates')

ajax_validate_login_bp = Blueprint("ajax_validate_login_bp", __name__,
                                      template_folder='templates')


@login_bp.route("/login", methods=["GET" ,"POST"])
def login():

    # method == "POST"
    if request.method == "POST":

        # 取得登入表單資料
        try:
            primary = request.values.get("primary")
            password = request.values.get("password")
            next_url = request.values.get("next_url")

            # 後端確認所有資料的格式，雖然前端已經過濾過
            check_result = helper.checkLoginFormat(primary, password)

        # 當有人故意送出奇怪的request
        except Exception as error:
            print(error)
            return render_template("error/403.html", error_message="Don't Play With Me."), 400


        # 如果有欄位的資料錯誤，則回傳之前端
        if check_result["primary_check"] == "failed" or \
            not check_result["password_check"]:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400

        user_to_login = helper.checkLogin(check_result["primary_check"], primary, password)

        if not user_to_login:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400
        
        if not user_to_login.is_authenticated:
            return render_template("activation/account_not_activated.html"), 401
        
        if not user_to_login.is_active:
            flash("此帳號已被凍結，<br>請聯絡管理人員以協助處理，謝謝", "danger")
            return redirect("/")

        # 以上所有註冊資料確認完成，可以註冊帳號
        else:
            login_user(user_to_login, remember=True, duration=datetime.timedelta(weeks=2))

            user_to_login.login_update()

            if next_url == "None":
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect("/"), 302

            if not helper.is_safe_url(next_url):
                return abort(400)
            else:
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect(next_url), 302

    # method == "GET"
    else:

        if current_user.is_authenticated:
            return redirect("/"), 302

        try:
            return render_template('account/login.html', next_url=request.args.get("next")), 200

        except TemplateNotFound:
            abort(404)


# 前端 ajax 驗證即將登入的表單資料是否通過登入驗證
@ajax_validate_login_bp.route("/ajax/validate/login/<primary_type_>/<primary_>/<password_>", methods=["POST"])
def ajax_validate_login(primary_type_, primary_, password_):

    # 預設為不通過
    result = {"login_pass": False}

    # 如果通過
    if helper.checkLogin(primary_type=primary_type_, primary=primary_, password=password_):
        result["login_pass"] = True

    # 回傳 json
    return jsonify(result)

caten_music/routes/logout.py
# routes/logout.py

from flask import Blueprint, render_template, abort, redirect, flash, request
from jinja2 import TemplateNotFound
from flask_login import logout_user, current_user


logout_bp = Blueprint("logout_bp", __name__,
                    template_folder='templates')


@logout_bp.route("/logout", methods=["POST"])
def logout():
    try:
        if current_user.is_authenticated:
            current_user.login_update()
        
        return_url = request.values.get('return_url')

        logout_user()
        flash("您已成功登出", "primary")
        return redirect(return_url), 302
    except:
        flash("發生錯誤，請回報管理員", "danger")
        return redirect("/"), 302

caten_music/routes/search.py
# routes/search.py

from flask import Blueprint, render_template, abort, request, redirect, current_app
from jinja2 import TemplateNotFound
from flask_login import current_user

import requests
import json

search_bp = Blueprint("search_bp", __name__,
                      template_folder='templates')


@search_bp.route('/search')
def search():

    if current_user.is_authenticated:
        current_user.login_update()

    # 關鍵字：標題
    primary = request.args.get("primary")

    # 搜尋模式
    searchMode = request.args.get("searchMode")

    # 關鍵字：歌詞
    # lyrics = request.args.get("lyrics")

    # 關鍵字：集數
    c = request.args.get("c")
    if c != "":
        return redirect("/"), 302

    # 關鍵字：語言
    lang = request.args.get("lang")
    if lang != "":
        return redirect("/"), 302

    # 關鍵字：調性
    to = request.args.get("to")
    if to != "":
        return redirect("/"), 302

    # API 串接搜尋
    if searchMode == "title":
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=&title=" + primary + "&lyrics=&test=0"
    if searchMode == "lyric":
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=&lyrics=" + primary + "&title=&test=0"
    r = requests.get(requestURL)

    if not r.status_code == 200:
        result = []
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, songs_num=len(result), mode="search", c=c, primary=primary, searchMode=searchMode), r.status_code
    except TemplateNotFound:
        abort(404)

caten_music/routes/surfer.py
# routes/surfer.py

from flask import Blueprint, render_template, abort, request, redirect, current_app
from jinja2 import TemplateNotFound

from flask_login import login_required, current_user

import requests
import json

surfer_bp = Blueprint("surfer_bp", __name__,
                      template_folder='templates')

surf_bp = Blueprint("surf_bp", __name__,
                    template_folder='templates')

surf_one_bp = Blueprint("surf_one_bp", __name__,
                        template_folder='templates')


@surfer_bp.route('/surfer')
def surfer():

    if current_user.is_authenticated:
        current_user.login_update()

    # Tonality Collection
    toColl = ["C", "Cm", "C#", "D", "Dm", "Db", "E", "Em", "Eb", "F",
              "Fm", "F#m", "G", "Gm", "Gb", "A", "Am", "Ab", "B", "Bm", "Bb"]

    try:
        return render_template("pages/surfer.html", toColl=toColl), 200
    except TemplateNotFound:
        abort(404)


@surf_bp.route('/surf')
def surf():

    if current_user.is_authenticated:
        current_user.login_update()

    surfMode = request.args.get("surfMode")
    requestURL = ""
    c = ""
    lang = ""
    to = ""

    if surfMode == "byLang":

        # 關鍵字：集數
        c = request.args.get("c").replace(" ", "")
        if c == "":
            return redirect("/"), 302

        # 關鍵字：語言
        lang = request.args.get("lang").replace(" ", "")
        if lang == "":
            return redirect("/"), 302

        # API 串接 搜尋
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=" + \
        lang + "&c=" + c + "&to=&title=&lyrics=&test=0"
    

    if surfMode == "byTo":

        # 關鍵字：調性
        to = request.args.get("to")
        if to == "":
            return redirect("/"), 302

        # API 串接 搜尋
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=" + to + "&title=&lyrics=&test=0"
    

    

    r = requests.get(requestURL)

    if not r.status_code == 200:
        result = []
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, songs_num=len(result), mode="surf", c=c, to=to, lang=lang, surfMode=surfMode), r.status_code

    except TemplateNotFound:
        abort(404)


@surf_one_bp.route('/song/<sid>')
def surf_one(sid):

    if current_user.is_authenticated:
        current_user.login_update()

    # API

    requestURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sid

    r = requests.get(requestURL)

    if not r.status_code == 200:
        return redirect("/")
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, mode="one"), r.status_code
    except TemplateNotFound:
        abort(404)

caten_music/templates/base/alert.html
<!-- Alert -->
<div id="alert" class="alert-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-setting fade show alert-height" role="alert" data-message="{{ message }}">
        <span class="alert-message"></span>
        <button class="d-none close close-this-alert"><i class="fas fa-times"></i></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

caten_music/templates/base/base.html
<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>

    {% block head %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caten Music{% block title %}{% endblock title%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Style -->
    {% block css %}

    {% include "base/style.html" %}

    {% endblock css %}

    {% endblock head%}

</head>

<body>

    
    {% block modal %}{% endblock modal %}
    
    {% block alert %}
    {% include "base/alert.html" %}
    {% endblock alert %}
    
    {% block navbar %}
    {% include "base/navbar.html" %}
    {% endblock navbar %}

    {% block jumbotron %}
    {% endblock jumbotron %}

    <div class="container">

        {% block header %}
        <!-- Header -->
        <header id="top-header">
            <div class="container">
                <h2 class="header-title">
                    {% block header_title %}{% endblock header_title %}
                </h2>
            </div>
            <div class="header-info-content">
                {% block header_info %}{% endblock header_info %}
            </div>
        </header>
        {% endblock header %}
    

        {% block main_hr %}
        <hr class="main-hr-bar">
        {% endblock main_hr %}

        <!-- Content -->
        <div id="content">
            {% block content %}{% endblock content%}
        </div>

        <!-- Footer -->
        {% block footer %}
        <footer id="footer">
            <p>&copy; 2019 &nbsp;Salt Chang.  
                <a href="https://github.com/saltchang/caten-music">GitHub</a>
            </p>
            <p>
                如有任何問題或建議，歡迎<a href="mailto:saltchang.tw@gmail.com">聯繫我</a>。
            </p>
            {% if env_state == "Development" %}
            <p>
                Development Mode
            </p>
            {% endif %}
        </footer>
        {% endblock %}

    </div>

    <!-- Script -->
    {% block script %}
    {% include "base/script.html" %}
    {% endblock script %}
</body>

</html>

{% block EOF_TAG %}{% endblock EOF_TAG %}

caten_music/templates/base/navbar.html
<!-- Navbar -->

{% set return_url = request.full_path | replace('/', '%2F') | replace('?', '%3F') | replace('=', '%3D') | replace('&', '%26') %}

<nav id="navbar" class="navbarstyle navbar navbar-expand-md navbar-light fixed-top">
    <a class="navbar-brand brand-logo-border" href="/">
        <svg width="3rem" height="3rem" viewBox="0 0 360 360" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!-- Generator: Sketch 55.2 (78181) - https://sketchapp.com -->
            <title>CatenMusicLogo</title>
            <desc>Created with Sketch.</desc>
            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <path d="M157.656406,358.626825 C68.7886879,347.624114 0,271.845286 0,180 C0,80.588745 80.588745,0 180,0 C279.411255,0 360,80.588745 360,180 C360,276.774201 283.630057,355.711245 187.870276,359.83103 C189.203863,359.662652 190.543049,359.465225 191.886749,359.238184 C229.904661,352.833945 257.758258,325.062356 256.45042,296.00688 C256.800641,294.415538 256.864776,292.719207 256.527716,291.016168 L222.389697,122.157125 C231.743202,123.995218 247.686028,129.420351 269.107316,145.162107 C304.722533,171.37039 316.87858,203.657302 316.87858,203.657302 C333.182501,171.960612 302.548776,127.937603 278.849809,111.458562 C262.301046,99.9498273 228.971332,75.9791077 210.342114,62.5395175 L203.842495,30.3627436 C202.576681,24.1149493 196.673695,20.1634582 190.636784,21.5688251 C184.600959,22.958734 180.741513,29.1606267 182.008438,35.4100178 L226.359584,254.797967 C212.282431,248.096823 194.582905,245.498101 175.970946,248.643034 C136.112925,255.352603 107.351185,285.569218 111.747298,316.107031 C114.820011,337.438754 133.24621,353.294756 157.656425,358.626829 Z" id="合併形狀" fill="#FFFFFF"></path>
            </g>
        </svg>
    </a>
    <a class="d-md-none" data-toggle="collapse" href="#navbarSupportedContent" role="button" aria-expanded="false"
        aria-controls="navbarSupportedContent" id="navbar-menu-btn">
        <span class="">
            <svg width="2rem" height="2rem" viewBox="0 0 330 330" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!-- Generator: Sketch 55.2 (78181) - https://sketchapp.com -->
            <title>menu_white</title>
            <desc>Created with Sketch.</desc>
            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <rect id="矩形" fill="#FFFFFF" x="0" y="0" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="120" y="0" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="240" y="0" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="0" y="120" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="120" y="120" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="240" y="120" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="0" y="240" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="120" y="240" width="90" height="90"></rect>
                <rect id="矩形" fill="#FFFFFF" x="240" y="240" width="90" height="90"></rect>
            </g>
        </svg>
    </span>
    </a>


    <div class="collapse navbar-collapse brand-menu-container navbar-content-list" id="navbarSupportedContent">

        <hr class="navbar-hr">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <form class="navbar-search-form" action="{{ url_for('search_bp.search') }}" method="GET">
                    <input class="d-none" type="text" name="c" value="">
                    <input class="d-none" type="text" name="lang" value="">
                    <input class="d-none" type="text" name="to" value="">
                    <input class="d-none" type="text" name="searchMode" value="title">
                    <input name="primary" type="text" class="navbar-input-search-songs-text form-control navbar-search fas"
                        placeholder="&#xf002; 快搜歌名">
                </form>
            </li>

            <hr class="navbar-hr">

            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('surfer_bp.surfer') }}">
                    <i class="fas fa-compass"></i>
                    &nbsp;探索
                    <span class="sr-only">(current)</span>
                </a>
            </li>

        </ul>

        <hr class="navbar-hr">

        <ul class="navbar-nav ml-auto">

            {% if current_user.is_admin %}
            <li class="nav-item active">
                <a class="nav-link navbar-item-style" href="{{ url_for('users_bp.users') }}">
                    <i class="fas fa-users"></i>
                    &nbsp;管理使用者
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            <hr class="navbar-hr">
            {% endif %}

            {% if not current_user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link navbar-item-style" href="{{ url_for('login_bp.login') + '?next=' + return_url }}">
                    <i class="fas fa-sign-in-alt"></i>
                    &nbsp;登入
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            <hr class="navbar-hr">

            <li class="nav-item active">
                <a class="nav-link navbar-item-style" href="{{ url_for('register_bp.register') }}">
                    <i class="fas fa-feather-alt"></i>
                    &nbsp;註冊
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}

            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
                <button class="dropdown-toggle btn-navbar-user-dropdown" type="button" data-toggle="collapse" data-target="#user-dropdown-collapse" aria-expanded="false">
                    <i class="fas fa-user"></i>
                    &nbsp;{{ current_user.displayname }}
                </button>
                <!-- <button class="dropdown-toggle" type="button" id="btn-navbar-user-dropdown" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {{ current_user.displayname }}
                </button> -->
                <div class="collapse dropdown-collapse" id="user-dropdown-collapse">
                <!-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"> -->
                    <!-- <a class="dropdown-item" href="/user/songlist">我的歌單</a> -->
                    <form action="{{ url_for('user_songlist_bp.user_songlist') }}" method="get">
                        <button type="submit" class="dropdown-item">我的歌單</button>
                    </form>
                    <form action="{{ url_for('logout_bp.logout') }}" method="post">
                        <input class="d-none" type="text" name="return_url" value="{{ request.full_path }}">
                        <button type="submit" class="dropdown-item">登出</button>
                    </form>
                </div>
            </li>
            {% endif %}

        </ul>

    </div>
</nav>

caten_music/templates/base/script.html
<!-- Local files -->

<!-- Popper 1.15.0 Local -->
<script src="{{ url_for('static', filename='js/lib/popper/popper.min.js') }}"></script>

<!-- JQuery 3.4.1 Local-->
<script src="{{ url_for('static', filename='js/lib/jquery/jquery.min.js') }}"></script>

<!-- JQuery UI 1.12.1 local -->
<script src="{{ url_for('static', filename='js/lib/jquery/jquery-ui.min.js') }}"></script>

<!-- JQuery UI Touch Punch local -->
<script src="{{ url_for('static', filename='js/lib/jquery/jquery.ui.touch-punch.min.js') }}"></script>

<!-- Bootstrap 4.3.1 Local-->
<script src="{{ url_for('static', filename='js/lib/bootstrap/bootstrap.min.js') }}"></script>

<!-- PDF.js -->
<!-- <script src="{{ url_for('static', filename='js/lib/pdf/pdf.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/pdf/pdf.worker.js') }}"></script> -->

<!-- base.js -->
<script src="{{ url_for('static', filename='js/base/base.js') }}"></script>

<!-- alert.js -->
<script src="{{ url_for('static', filename='js/base/alert.js') }}"></script>

caten_music/templates/base/style.html
<!-- Reset all css first -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/reset.css') }}">

<!-- Font CDN -->

<!-- Google Font - Gramond -->
<link href="https://fonts.googleapis.com/css?family=EB+Garamond:400,500" rel="stylesheet">

<!-- Google Font - Noto Sans TC & Noto Serif TC -->
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC|Noto+Serif+TC:400,500&amp;subset=chinese-traditional"
    rel="stylesheet">

<!--Local Files -->

<!-- Bootstrap 4.3.1 Local-->
<link href="{{ url_for('static', filename='css/lib/bootstrap/bootstrap.min.css') }}" rel="stylesheet">

<!-- FontAwesome 5.8.2 Local-->
<link href="{{ url_for('static', filename='css/lib/fontAwesome/css/all.min.css') }}" rel="stylesheet">


<!-- base.css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/base.css') }}">

<!-- Replace_bootstrap.css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/replace_bootstrap.css') }}">


<!-- header.css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/header.css') }}">

<!-- navbar.css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/navbar.css') }}">

<!-- alert.css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/base/alert.css') }}">

<!-- favicon.ico as shortcut icon -->
<link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">