caten_music/routes/home.py
# routes/home.py

from flask import Blueprint, render_template, abort, flash, current_app
from jinja2 import TemplateNotFound

from flask_login import current_user

import random
import requests
import json
import os

home_bp = Blueprint("home_bp", __name__,
                    template_folder='templates')


@home_bp.route('/')
def seeHome():

    result = []

    random_amount = str(6)

    if current_user.is_authenticated:
        current_user.login_update()

        requestURL = "https://church-music-api.herokuapp.com/api/songs/random/" + random_amount
        r = requests.get(requestURL)

        if r.status_code == 200:
            result = json.loads(r.text)
            
    
    env_state = os.environ.get("APP_SETTING")
    return render_template("pages/home.html", songs=result, env_state=env_state), 200

caten_music/routes/login.py
# routes/login.py

from flask import Blueprint, render_template, abort, jsonify, request, redirect, url_for, flash
from jinja2 import TemplateNotFound
from flask_login import login_user, current_user

import datetime

from caten_music import helper


login_bp = Blueprint("login_bp", __name__,
                    template_folder='templates')

ajax_validate_login_bp = Blueprint("ajax_validate_login_bp", __name__,
                                      template_folder='templates')


@login_bp.route("/login", methods=["GET" ,"POST"])
def login():

    # method == "POST"
    if request.method == "POST":

        # 取得登入表單資料
        try:
            primary = request.values.get("primary")
            password = request.values.get("password")
            next_url = request.values.get("next_url")

            # 後端確認所有資料的格式，雖然前端已經過濾過
            check_result = helper.checkLoginFormat(primary, password)

        # 當有人故意送出奇怪的request
        except Exception as error:
            print(error)
            return render_template("error/403.html", error_message="Don't Play With Me."), 400


        # 如果有欄位的資料錯誤，則回傳之前端
        if check_result["primary_check"] == "failed" or \
            not check_result["password_check"]:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400

        user_to_login = helper.checkLogin(check_result["primary_check"], primary, password)

        if not user_to_login:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400
        
        if not user_to_login.is_authenticated:
            return render_template("activation/account_not_activated.html"), 401
        
        if not user_to_login.is_active:
            flash("此帳號已被凍結，<br>請聯絡管理人員以協助處理，謝謝", "danger")
            return redirect("/")

        # 以上所有註冊資料確認完成，可以註冊帳號
        else:
            login_user(user_to_login, remember=True, duration=datetime.timedelta(weeks=2))

            user_to_login.login_update()

            if next_url == "None":
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect("/"), 302

            if not helper.is_safe_url(next_url):
                return abort(400)
            else:
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect(next_url), 302

    # method == "GET"
    else:

        if current_user.is_authenticated:
            return redirect("/"), 302

        try:
            return render_template('account/login.html', next_url=request.args.get("next")), 200

        except TemplateNotFound:
            abort(404)


# 前端 ajax 驗證即將登入的表單資料是否通過登入驗證
@ajax_validate_login_bp.route("/ajax/validate/login/<primary_type_>/<primary_>/<password_>", methods=["POST"])
def ajax_validate_login(primary_type_, primary_, password_):

    # 預設為不通過
    result = {"login_pass": False}

    # 如果通過
    if helper.checkLogin(primary_type=primary_type_, primary=primary_, password=password_):
        result["login_pass"] = True

    # 回傳 json
    return jsonify(result)

caten_music/routes/register.py
# routes/register.py

from flask import Blueprint, render_template, abort, request, redirect, jsonify, current_app, flash, url_for
from jinja2 import TemplateNotFound
from flask_login import current_user

from caten_music import services
from caten_music import helper
from caten_music import models

User = models.User
UserProfile = models.UserProfile
checkExist = helper.checkExist()

register_bp = Blueprint("register_bp", __name__,
                        template_folder='templates')

ajax_validate_register_bp = Blueprint("ajax_validate_register_bp", __name__,
                                      template_folder='templates')

show_user_bp = Blueprint("show_user_bp", __name__,
                              template_folder='templates')

# 註冊
@register_bp.route('/register', methods=["GET", "POST"])
def register():

    username = ""
    email = ""
    password = ""

    # method == "POST"
    if request.method == "POST":

        # 取得註冊表單資料
        try:
            username = request.values.get("username")
            email = request.values.get("email")
            displayname = request.values.get("displayname")
            password = request.values.get("password")
            confirm_password = request.values.get("confirm_password")

            # 後端確認所有資料的格式，雖然前端已經過濾過
            check_result = helper.checkFormat(
                username, email, displayname, password)

        # 當有人故意送出奇怪的request
        except:
            return render_template("error/403.html", error_message="Don't Play With Me."), 400

        # 如果有欄位的資料錯誤，則回傳之前端
        for k, v in check_result.items():
            if not v:
                return render_template("error/403.html", error_message="Wrong " + k.replace("_check", "")), 400

        # 如果兩次輸入的密碼不一樣
        if not password == confirm_password:
            return render_template("error/403.html", error_message="兩次輸入的密碼不一樣，請再試一次"), 400

        # 檢查 username 是否已註冊
        if checkExist.username(username=username):
            return render_template("error/403.html", error_message="使用者名稱已被註冊"), 400

        # 檢查 email 是否已註冊
        if checkExist.email(email=email):
            return render_template("error/403.html", error_message="電子信箱已被註冊"), 400

        # 以上所有註冊資料確認完成，可以註冊帳號

        # 建立新的使用者物件
        new_user = User(
            username=username, email=email, displayname=displayname, password=password)

        # 提交新使用者至資料庫中儲存
        new_user.save()

        # 產生新的使用者檔案並提交儲存
        new_user_profile = UserProfile(user_id=new_user.id)
        new_user_profile.save()

        # 產生一個帳號啟動的 token
        token = new_user.create_activate_token()

        # 啟動 mail 服務
        # 寄出帳號啟動 email
        services.send_mail(sender='Sender@domain.com',
                               recipients=[email],
                               subject='Caten music 帳號註冊認證信',
                               template='activation/verifymail.html',
                               username=username,
                               mail_title="帳號註冊認證信",
                               message="歡迎你, 請點擊下面連結來啟用您的帳號",
                               link_msg="點此啟用您的帳號",
                               link_url=url_for('activate_account_bp.activate_account', gate="account_activate", token=token, _external=True),
                               token=token)

        # 註冊完成，通知使用者收取認證信
        try:
            return render_template("activation/after_register.html", msg_text="註冊資料已送出"), 201

        except TemplateNotFound:
            abort(404)

    # method = "GET"
    else:

        if current_user.is_authenticated:
            return redirect("/"), 302

        # 產生註冊表單
        try:
            return render_template("account/register.html"), 200

        except TemplateNotFound:
            abort(404)


# 前端 ajax 驗證即將註冊的表單資料是否重複 username 或 email
@ajax_validate_register_bp.route("/ajax/validate/register/<username_>/<email_>", methods=["POST"])
def ajax_validate_register(username_, email_):

    # 預設為不存在
    result = {"username": False, "email": False}

    # 如果 username 已經存在，則回傳 True
    if checkExist.username(username=username_):
        result["username"] = True

    # 如果 email 已經存在，則回傳 True
    if checkExist.email(email=email_):
        result["email"] = True

    # 回傳 json
    return jsonify(result)


# 顯示目前所有使用者 (開發用途)
@show_user_bp.route("/show/user/<username>")
def show_user(username):
    user = User.query.filter_by(username=username).first_or_404()

    return render_template("account/show_user.html", user=user), 200

caten_music/routes/search.py
# routes/search.py

from flask import Blueprint, render_template, abort, request, redirect, current_app
from jinja2 import TemplateNotFound
from flask_login import current_user

import requests
import json

search_bp = Blueprint("search_bp", __name__,
                      template_folder='templates')


@search_bp.route('/search')
def search():

    if current_user.is_authenticated:
        current_user.login_update()

    # 關鍵字：標題
    primary = request.args.get("primary")

    # 搜尋模式
    searchMode = request.args.get("searchMode")

    # 關鍵字：歌詞
    # lyrics = request.args.get("lyrics")

    # 關鍵字：集數
    c = request.args.get("c")
    if c != "":
        return redirect("/"), 302

    # 關鍵字：語言
    lang = request.args.get("lang")
    if lang != "":
        return redirect("/"), 302

    # 關鍵字：調性
    to = request.args.get("to")
    if to != "":
        return redirect("/"), 302

    # API 串接搜尋
    if searchMode == "title":
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=&title=" + primary + "&lyrics=&test=0"
    if searchMode == "lyric":
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=&lyrics=" + primary + "&title=&test=0"
    r = requests.get(requestURL)

    if not r.status_code == 200:
        result = []
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, songs_num=len(result), mode="search", c=c, primary=primary, searchMode=searchMode), r.status_code
    except TemplateNotFound:
        abort(404)

caten_music/routes/surfer.py
# routes/surfer.py

from flask import Blueprint, render_template, abort, request, redirect, current_app
from jinja2 import TemplateNotFound

from flask_login import login_required, current_user

import requests
import json

surfer_bp = Blueprint("surfer_bp", __name__,
                      template_folder='templates')

surf_bp = Blueprint("surf_bp", __name__,
                    template_folder='templates')

surf_one_bp = Blueprint("surf_one_bp", __name__,
                        template_folder='templates')


@surfer_bp.route('/surfer')
def surfer():

    if current_user.is_authenticated:
        current_user.login_update()

    # Tonality Collection
    toColl = ["C", "Cm", "C#", "D", "Dm", "Db", "E", "Em", "Eb", "F",
              "Fm", "F#m", "G", "Gm", "Gb", "A", "Am", "Ab", "B", "Bm", "Bb"]

    try:
        return render_template("pages/surfer.html", toColl=toColl), 200
    except TemplateNotFound:
        abort(404)


@surf_bp.route('/surf')
def surf():

    if current_user.is_authenticated:
        current_user.login_update()

    surfMode = request.args.get("surfMode")
    requestURL = ""
    c = ""
    lang = ""
    to = ""

    if surfMode == "byLang":

        # 關鍵字：集數
        c = request.args.get("c").replace(" ", "")
        if c == "":
            return redirect("/"), 302

        # 關鍵字：語言
        lang = request.args.get("lang").replace(" ", "")
        if lang == "":
            return redirect("/"), 302

        # API 串接 搜尋
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=" + \
        lang + "&c=" + c + "&to=&title=&lyrics=&test=0"
    

    if surfMode == "byTo":

        # 關鍵字：調性
        to = request.args.get("to")
        if to == "":
            return redirect("/"), 302

        # API 串接 搜尋
        requestURL = "https://church-music-api.herokuapp.com/api/songs/search?lang=&c=&to=" + to + "&title=&lyrics=&test=0"
    

    

    r = requests.get(requestURL)

    if not r.status_code == 200:
        result = []
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, songs_num=len(result), mode="surf", c=c, to=to, lang=lang, surfMode=surfMode), r.status_code

    except TemplateNotFound:
        abort(404)


@surf_one_bp.route('/song/<sid>')
def surf_one(sid):

    if current_user.is_authenticated:
        current_user.login_update()

    # API

    requestURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sid

    r = requests.get(requestURL)

    if not r.status_code == 200:
        return redirect("/")
    else:
        result = json.loads(r.text)

    try:
        return render_template("songs/songs.html", songs=result, mode="one"), r.status_code
    except TemplateNotFound:
        abort(404)

caten_music/templates/pages/home.html
<!-- templates/index.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/pages/home.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/songs/home_song_card.css') }}">
{%  endblock  %}

{% block title %}{% endblock %}

{% block header %}{% endblock header %}

{% block main_hr %}{% endblock main_hr %}

{% block jumbotron %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <!-- <h1 class="display-4">Fluid jumbotron</h1> -->
        <p class="bible-text">
            “ 在列邦中述說他的榮耀！在萬民中述說他的奇事！”
        </p>
        <p class="bible-tag">
            - 詩篇 96:3
        </p>
    </div>
</div>
{% endblock jumbotron %}

{% block content%}
{% if not current_user.is_authenticated %}
<div class="row row-card">

    <div class="col-12 col-lg-8 col-card">
        <div class="card card-home-register">
            <h1>
                <!-- 尋見 <i class="fas fa-times"></i> 分享 -->
                尋見 ✕ 分享
                <!-- <br class="d-sm-none"> -->
            </h1>
            <div class="container text-center">
                <p>
                    Caten Music 是一個音樂資料平台。
                    這裡收集了每首歌曲的詳盡資料，並提供快速方便的檢索方式以及歌單功能。
                    從此不用再為了回想歌曲的名字而煩惱！
                    <br>
                    <b>快速查找歌曲 + 整理歌單！</b>
                    然後分享給你的<b>朋友、組員、同工！</b>
                    現在就開始使用音樂資料庫吧！
                </p>
            </div>
            <a class="btn" href="{{ url_for('register_bp.register') }}">註冊 Caten Music</a>
        </div>
    </div>

    <div class="col-12 col-lg-4 col-card">
        <div class="card card-home-login">
            <h1>
                已經有帳號？
            </h1>
            <a class="btn" href="{{ url_for('login_bp.login') + '?next=' }}">登入 Caten Music</a>
        </div>
    </div>

</div>

{% endif %}

{% if current_user.is_authenticated %}

<div class="random-songs-card">
    <div id="carouselExampleControls" class="carousel slide carousel-container" data-ride="carousel">
        <h1 class="random-recommend">推薦</h1>
        <div class="carousel-inner">

            {% for index in range(songs | length) %}
            {% set song = songs[index] %}
            {% if index == 0 %}
            <div class="carousel-item active">
                <div class="d-block w-100">
                    {% include "songs/home_song_card.html" %}
                </div>
            </div>
            {% else %}
            <div class="carousel-item">
                <div class="d-block w-100">
                    {% include "songs/home_song_card.html" %}
                </div>
            </div>
            {% endif %}
            {% endfor %}

        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

{% endif %}


<div class="container search-container">

    <div class="container text-center">
        <form action="{{ url_for('search_bp.search') }}" method="GET">
            <input class="d-none" type="text" name="c" value="">
            <input class="d-none" type="text" name="lang" value="">
            <input class="d-none" type="text" name="to" value="">
            <div class="form-group row m-0">
                <div class="col-sm-1 col-lg-2"></div>
                <div class="col p-0 p-md-3">
                    <!-- <h3 class="quick-search">快速搜尋</h3> -->
                    <div class="row m-0 justify-content-around">
                        <input name="primary" type="text" class="col-9 input-search-songs-text form-control"
                            id="search-text" placeholder="搜尋">
                        <button type="submit" class="col-2 btn button-search-songs"><i
                                class="fas fa-search"></i></button>
                    </div>
                    <div class="check-search-mode">
                        <span>
                            <input class="" type="radio" name="searchMode" id="radio-check-search-mode-title"
                                value="title" checked>
                            <label class="" for="radio-check-search-mode-title">
                                找歌名
                            </label>
                        </span>
                        <span>
                            <input class="" type="radio" name="searchMode" id="radio-check-search-mode-lyric"
                                value="lyric">
                            <label class="" for="radio-check-search-mode-lyric">
                                找歌詞
                            </label>
                        </span>

                    </div>
                </div>
                <div class="col-sm-1 col-lg-2"></div>
            </div>

        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{{  super ()  }}
<script src="{{ url_for('static', filename='js/songs/home_song_card.js') }}"></script>
{% endblock script %}

{% block EOF_TAG %}
<!-- EOF templates/index.html -->
{% endblock EOF_TAG %}

caten_music/templates/pages/surfer.html
<!-- templates/surfer.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
<link rel="stylesheet" href="static/css/pages/surfer.css">
{%  endblock  %}

{% block title %} - 探索{% endblock %}

{% block header_title %}探索歌曲{% endblock header_title %}

{% block content%}
<div class="container text-center">

    <div class="surfer-block">
        <h5 class="surfer-tag">
            <a class="" data-toggle="collapse" href="#byLanguage" role="button" aria-expanded="false"
                aria-controls="byLanguage">
                語言分類&nbsp;
                <i class="fas fa-chevron-down"></i>
            </a>
        </h5>
        <div class="collapse" id="byLanguage">
            <div class="container text-center p-md-0">
                <div id="language-surfer">
                    <div class="row">
                        <div class="col lang-tag">國語</div>
                        <div class="col lang-tag">台語</div>
                    </div>
                    <div class="row">
                        <div class="col px-0 pr-md-3">
                            <div class="row mx-0 p-0">
                                {% for i in range(1, 12) %}
                                <div class="col-12 col-md-6 col-xl-4">
                                    <form action="{{ url_for('surf_bp.surf') }}" method="GET">
                                        <input class="d-none" type="text" name="surfMode" value="byLang">
                                        <input class="d-none" type="text" name="lang" value="Chinese">
                                        <button type="submit" class="btn chinese-surf-btn" name="c" value="{{ i }}">
                                            第 {{ i }} 集
                                        </button>
                                    </form>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col px-0 pl-md-3">
                            <div class="row mx-0 p-0">
                                {% for i in range(1, 11) %}
                                <div class="col-12 col-md-6 col-xl-4">
                                    <form action="{{ url_for('surf_bp.surf') }}" method="GET">
                                        <input class="d-none" type="text" name="surfMode" value="byLang">
                                        <input class="d-none" type="text" name="lang" value="Taiwanese">
                                        <button type="submit" class="btn taiwanese-surf-btn" name="c" value="{{ i }}">
                                            第 {{ i }} 集
                                        </button>
                                    </form>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="surfer-block">
        <h5 class="surfer-tag">
            <a class="" data-toggle="collapse" href="#byTonality" role="button" aria-expanded="false"
                aria-controls="byTonality">
                調性分類&nbsp;
                <i class="fas fa-chevron-down"></i>
            </a>
        </h5>
        <div class="collapse" id="byTonality">
            <div class="container text-center p-md-0">
                <div id="tonality-surfer">
                    <div class="row">

                        {% for toC in toColl %}
                        <div class="col-4">
                            <form action="{{ url_for('surf_bp.surf') }}" method="GET">
                                <input class="d-none" type="text" name="surfMode" value="byTo">
                                <input class="d-none" type="text" name="to" value="{{ toC }}">
                                <button type="submit" class="btn tonality-surf-btn">
                                    {{ toC }}
                                </button>
                            </form>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{{  super ()  }}
<script src="{{ url_for('static', filename='js/pages/surfer.js') }}"></script>
{% endblock script %}

{% block EOF_TAG %}
<!-- EOF templates/surfer.html -->
{% endblock EOF_TAG %}