caten_music/routes/admin.py
# routes/admin.py

from flask import Blueprint, render_template, abort, flash, current_app, request, redirect, jsonify, url_for
from jinja2 import TemplateNotFound

from caten_music.models import User, login_manager
from caten_music import helper

from flask_login import login_required, current_user

import requests
import json
import os
import re

song_edit_bp = Blueprint("song_edit_bp", __name__,
                    template_folder='templates')

users_bp = Blueprint("users_bp", __name__,
                    template_folder='templates')

user_edit_bp = Blueprint("user_edit_bp", __name__,
                    template_folder='templates')


@song_edit_bp.route('/admin/edit/song/<sid>', methods=["GET", "POST"])
@login_required
def edit(sid):

    # 更新使用者登入時間
    if current_user.is_authenticated:
        current_user.login_update()
    
    # 確認使用者擁有管理員權限
    if not current_user.is_manager:
        flash("很抱歉，您並沒有編輯歌曲的權限。", "danger")
        return redirect("/")

    # Get 歌曲資訊
    requestURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sid

    r = requests.get(requestURL)

    if not r.status_code == 200:
        flash("錯誤的資訊", "danger")
        return redirect("/")
    else:
        result = json.loads(r.text)
        song = result[0]

    if request.method == "GET":

        return_url = request.values.get("next")
        
        # Tonality Collection
        toColl = ["C", "Cm", "C#", "D", "Dm", "Db", "E", "Em", "Eb", "F",
                  "Fm", "F#m", "G", "Gm", "Gb", "A", "Am", "Ab", "B", "Bm", 
                  "Bb"]
        
        # Get original titles
        song_title_original = ""
        len_title_o = len(song["title_original"])
        if len_title_o > 0:
            for i in range(len_title_o):
                if i == (len_title_o - 1):
                    song_title_original += song["title_original"][i]
                else:
                    song_title_original += song["title_original"][i] + " / "
        
        # Get lyrics
        song_lyrics = ""
        for p in song["lyrics"]:
            song_lyrics += p + "\n"

        return render_template("admin/song_edit.html", song=song, toColl=toColl, song_lyrics=song_lyrics, song_title_original=song_title_original, return_url=return_url)
    
    elif request.method == "POST":

        try:

            return_url = request.values.get("return_url")

            # 編輯歌曲時，不可更改語言、編號、sid
            # num_c = request.values.get("num_c")
            # num_i = request.values.get("num_i")
            # language = request.values.get("language")

            num_c = song["num_c"]
            num_i = song["num_i"]
            language = song["language"]

            # 取得表單資料
            title = request.values.get("title")
            originalTitleOriginal = request.values.get("title_original")
            scripture = request.values.get("scripture")
            tonality = request.values.get("tonality")
            year = request.values.get("year")
            lyricist = request.values.get("lyricist")
            composer = request.values.get("composer")
            translator = request.values.get("translator")
            album = request.values.get("album")
            publisher = request.values.get("publisher")
            publisher_original = request.values.get("publisher_original")
            tempo = request.values.get("tempo")
            time_signature = request.values.get("time_signature")

            originLyrics = request.values.get("lyrics")

            # 編輯歌曲時，不可更改語言、編號、sid
            # sid = ""
            # if language == "Chinese":
            #     sid += "1"
            # else:
            #     sid += "2"

            # if len(num_c) < 2:
            #     sid += "00" + num_c
            # else:
            #     sid += "0" + num_c

            # if len(num_i) < 2:
            #     sid += "00" + num_i
            # else:
            #     sid += "0" + num_i

            title_original_old = originalTitleOriginal.split("/")
            title_original = []
            for title_o in title_original_old:
                title_o = title_o.strip()
                if len(title_o) > 0:
                    title_original.append(title_o)
            
            lyrics_old = originLyrics.split("\n")
            lyrics = []
            
            lyrics_len = len(lyrics_old)
            for i in range(lyrics_len):
                p = lyrics_old[i]
                if len(p) > 0:
                    p = p.strip()
                    p = p.replace("\n", "")
                    p = p.replace("\r", "")
                if len(p) > 0:
                    lyrics.append(p)

            mostAdminToken = os.environ.get("SONGS_DB_MOST_ADMIN_TOKEN")

            newSong = {
                "sid": sid,
                "num_c": num_c,
                "num_i": num_i,
                "title": title,
                "title_original": title_original,
                "scripture": scripture,
                "year": year,
                "lyricist": lyricist,
                "composer": composer,
                "translator": translator,
                "lyrics": lyrics,
                "tonality": tonality,
                "tempo": tempo,
                "time_signature": time_signature,
                "album": album,
                "publisher": publisher,
                "publisher_original": publisher_original,
                "language": language,
                "token" : mostAdminToken,
            }

            newSong_json = json.dumps(newSong)

            putURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sid
            # putURL = "http://0.0.0.0:7700/api/songs/sid/" + sid

            r_put = requests.put(putURL, newSong_json)

            response = json.loads(r_put.text)
            # return r_put.text

            
            if not helper.is_safe_url(return_url):
                flash("不安全的連結", "danger")
                return abort(400)
            else:
                if not return_url:
                    return redirect("/")
                flash("成功編輯歌曲 #" + sid, "success")
                return redirect(return_url)
        
        except Exception as error:
            print(error)
            flash("發生錯誤，請洽網站管理員。", "danger")
            return redirect("/")

@users_bp.route('/admin/users', methods=['GET'])
@login_required
def users():

    # 更新使用者登入時間
    if current_user.is_authenticated:
        current_user.login_update()

    if not current_user.is_admin:
        flash("您並沒有管理員權限。", "danger")
        return redirect("/")

    if request.method == "GET":
        users = User.query.order_by(User.id).all()
        return render_template("admin/users.html", users=users)

@user_edit_bp.route('/admin/users/edit/<id_>', methods=['GET', 'POST'])
@login_required
def edit(id_):

    # 更新使用者登入時間
    if current_user.is_authenticated:
        current_user.login_update()

    if not current_user.is_admin:
        flash("您並沒有總管理員權限。", "danger")
        return redirect("/")
    
    if request.method == "GET":
        user = User.query.filter_by(id=id_).first()
        return render_template("admin/user_edit.html", user=user)

    elif request.method == "POST":
        
        try:
            user = User.query.filter_by(id=id_).first()
        except:
            flash("錯誤的使用者資訊", "danger")
        
        displayname = request.values.get("displayname")
        authority = request.values.get("authority")

        # 確認顯示名稱格式
        if re.fullmatch(r"^[\u4e00-\u9fa5_a-zA-Z0-9]{1,17}$", displayname):
            stringLen = 0

            for c in displayname:
                if re.fullmatch(r"^[\u4e00-\u9fa5]+$", c):
                    stringLen += 2
                else:
                    stringLen += 1

            if stringLen <= 16:
                user.displayname = displayname
            
            else:
                flash("編輯使用者顯示名稱時發生錯誤", "danger")
                return redirect("/")
        else:
            flash("編輯使用者顯示名稱時發生錯誤", "danger")
            return redirect("/")
        
        # 確認權限
        if authority == "admin":
            user.is_admin = True
            user.is_manager = True
        elif authority == "manager":
            user.is_admin = False
            user.is_manager = True
        elif authority == "normal":
            user.is_admin = False
            user.is_manager = False
        else:
            flash("編輯使用者權限時發生錯誤", "danger")
            return redirect("/")
        
        user.update()

        return redirect(url_for("users_bp.users"))

caten_music/routes/songlist.py
# routes/user_songlist.py

from flask import Blueprint, render_template, abort, flash, current_app, request, redirect, jsonify, url_for
from jinja2 import TemplateNotFound

from caten_music.models import SongList, User, login_manager

from flask_login import login_required, current_user

import requests
import json

user_songlist_bp = Blueprint("user_songlist_bp", __name__,
                    template_folder='templates')

song_list_by_id_bp = Blueprint("song_list_by_id_bp", __name__,
                    template_folder='templates')

add_songlist_bp = Blueprint("add_songlist_bp", __name__,
                    template_folder='templates')

songlist_edit_bp = Blueprint("songlist_edit_bp", __name__,
                    template_folder='templates')

songlist_delete_bp = Blueprint("songlist_delete_bp", __name__,
                    template_folder='templates')

ajax_update_songlist_bp = Blueprint("ajax_update_songlist_bp", __name__,
                    template_folder='templates')


@user_songlist_bp.route('/user/songlist')
@login_required
def user_songlist():

    if current_user.is_authenticated:
        current_user.login_update()

    try:
        return render_template("songs/list_of_songlist.html"), 200

    except TemplateNotFound:
        abort(404)

@songlist_delete_bp.route("/songlist/delete/<out_id>", methods=["POST"])
@login_required
def delete(out_id):

    if current_user.is_authenticated:
        current_user.login_update()

    if request.method == "POST":

        songlist = SongList.query.filter_by(out_id=out_id).first()

        if not songlist:
            flash("錯誤的歌單資訊", "danger")
            return redirect("/")

        if songlist.user_id == current_user.id:
            songlist.kill_self()
            flash("已成功刪除歌單 #" + out_id, "success")
            return redirect(url_for("user_songlist_bp.user_songlist"))
    
        else:
            flash("想幹嘛？您沒有權限刪除此歌單。<br>請登入後再試一次。", "danger")

    else:

        return redirect("/")


@song_list_by_id_bp.route('/songlist/<out_id>')
def song_list_by_id(out_id):

    if current_user.is_authenticated:
        current_user.login_update()

    songs = []

    songlist = SongList.query.filter_by(out_id=out_id).first()

    if not songlist:
        flash("錯誤的歌單資訊", "danger")
        return redirect("/")

    listowner = User.query.filter_by(id=songlist.user_id).first()

    if songlist.is_private:
        if not current_user.is_authenticated:
            flash("您目前造訪的是一份私人歌單，<br>請先確認您擁有此歌單的權限。", "danger")
            return redirect("/")
            
        if current_user.id != listowner.id:
            flash("您目前造訪的是一份私人歌單，<br>請先確認您擁有此歌單的權限。", "danger")
            return redirect("/")

    sids = ""
    for i in range(len(songlist.songs_sid_list)):
        if i == 0:
            sids += songlist.songs_sid_list[i]
        else:
            sids += "+" + songlist.songs_sid_list[i]
    
    requestURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sids
    r = requests.get(requestURL)
    if r.status_code == 200:
        songs = json.loads(r.text)
    elif r.status_code == 404:
        songs = []

    old_description = songlist.description
    
    new_description = old_description.replace("\r\n", "<br>")

    try:
        return render_template("songs/songlist.html", songs=songs, songlist=songlist, listowner=listowner, new_description=new_description), 200

    except TemplateNotFound:
        abort(404)

@songlist_edit_bp.route('/songlist/edit/<out_id>', methods=["GET", "POST"])
@login_required
def edit(out_id):

    if current_user.is_authenticated:
        current_user.login_update()

    songlist = SongList.query.filter_by(out_id=out_id).first()

    if not songlist:
        flash("錯誤的歌單資訊", "danger")
        return redirect("/")

    if current_user.id != songlist.user_id:
        flash("想幹嘛？你沒有權限編輯此歌單。<br>請登入後再試一次。", "danger")
        return redirect("/")

    if request.method == "GET":

        songs = []

        sids = ""
        for i in range(len(songlist.songs_sid_list)):
            if i == 0:
                sids += songlist.songs_sid_list[i]
            else:
                sids += "+" + songlist.songs_sid_list[i]
        
        requestURL = "https://church-music-api.herokuapp.com/api/songs/sid/" + sids
        r = requests.get(requestURL)
        if r.status_code == 200:
            songs = json.loads(r.text)
        elif r.status_code == 404:
            songs = []

        return render_template("songs/songlist_edit.html", songlist=songlist, songs=songs)
    
    elif request.method == "POST":

        title = request.values.get("title")

        description = request.values.get("description")

        is_private = False

        if request.values.get("privacy") == "private":
            is_private = True
        
        is_archived = False

        if request.values.get("archive") == "archived":
            is_archived = True

        songs_amount = int(request.values.get("songs_amount"))

        songs_sid_list_new = []

        for index in range(songs_amount):
            songs_sid_list_new.append(request.values.get(str(index)))

        songlist.title = title
        songlist.description = description
        songlist.is_private = is_private
        songlist.is_archived = is_archived
        songlist.songs_amount = songs_amount

        songlist.songs_sid_list = None
        songlist.update()
        songlist.refresh()

        songlist.songs_sid_list = songs_sid_list_new

        songlist.update()

        return redirect(url_for("song_list_by_id_bp.song_list_by_id", out_id=out_id))


@add_songlist_bp.route('/songlist/add', methods=["GET", "POST"])
@login_required
def add_songlist():

    if current_user.is_authenticated:
        current_user.login_update()

    if request.method == "POST":
        posttype = request.values.get("posttype")
        title = request.values.get("title")
        privacy = request.values.get("privacy")

        is_private = False

        if posttype == "withsong":
            song_sid = request.values.get("song_sid")
            if privacy == "private":
                is_private = True
                
            new_songlist = SongList(title=title, user=current_user, songs_sid_list=[song_sid], songs_amount=1, is_private=is_private)

            new_songlist.flush()

            new_songlist.init()

            new_songlist.save()

            return render_template("songs/list_of_songlist.html"), 200

    else:
        try:
            return render_template("songs/list_of_songlist.html"), 200

        except TemplateNotFound:
            abort(404)


@ajax_update_songlist_bp.route('/ajax/update/songlist/<song_sid>/<songlist_outid>', methods=["PUT"])
@login_required
def update_songlist(song_sid, songlist_outid):

    if current_user.is_authenticated:
        current_user.login_update()
    
    if request.method == "PUT":

        songlist = SongList.query.filter_by(out_id=songlist_outid).first()

        if not songlist:
            return jsonify({"success": False, "message": "wrong out_id"})

        tempList = songlist.songs_sid_list
        songlist.songs_sid_list = None
        songlist.update()
        songlist.refresh()

        
        if song_sid in tempList:
            tempList.remove(song_sid)
            songlist.songs_amount -= 1

            songlist.songs_sid_list = tempList

            songlist.update()

            return jsonify({"success": True, "act": "remove", "song": song_sid, "songlist": songlist_outid})

        else:
            tempList.append(song_sid)
            songlist.songs_amount += 1

            songlist.songs_sid_list = tempList

            songlist.update()

            return jsonify({"success": True, "act": "append", "song": song_sid, "songlist": songlist_outid})
    
    else:

        return jsonify({"success": False, "message": "wrong method"})

caten_music/templates/songs/home_song_card.html
<div id="{{ 'song-card-id-' + index | string }}" class="card home-song-card">
    <h1>
        {{ song.title }}
    </h1>
    <div class="container text-center">
        <div class="song-info">
                {% if song.language == "Chinese" %}
                國
                {% endif %}
                {% if song.language == "Taiwanese" %}
                台
                {% endif %}
                &nbsp;
                {{ song.num_c }}&nbsp;-&nbsp;{{ song.num_i }}
            <span class="space-block"></span>
                {{ song.tonality }}&nbsp;調
        </div>
    </div>
    <a class="btn" href="{{ url_for('surf_one_bp.surf_one', sid=song.sid) }}">查看這首歌</a>
</div>

caten_music/templates/songs/song_card.html
<!-- templates/songs/song_card.html -->

{% set return_url = request.full_path | replace('/', '%2F') | replace('?', '%3F') | replace('=', '%3D') | replace('&', '%26') %}

<div class="song-card row m-0">
    <div class="col-md-1 col-lg-2"></div>
    <div class="col card my-3 p-0">
        <h4 class="card-header">

            <div class="row card-header__row">
                <div class="p-0 col-1 card-header__icon">
                    <!-- 管理員權限 -->
                    {% if current_user.is_manager %}
                    <a class="edit-icon"
                        href="{{ url_for('song_edit_bp.edit', sid=song.sid) + '?next=' + return_url }}">
                        <i class="fas fa-feather-alt"></i>
                    </a>
                    {% endif %}
                    <!-- 管理員權限 -->
                </div>

                {% set len_song_title_original = song.title_original | length %}

                <div class="p-0 col-10 card-header__text">
                    {% if len_song_title_original > 0 %}
                    <h4 class="header-title-text--with-original">
                        {{ song.title }}
                    </h4>
                    <p class="header-title-text--original">
                        {% for i in range(len_song_title_original) %}
                        {{ song.title_original[i] }}
                        {% if not i == len_song_title_original - 1 %}
                        {{ " / " }}
                        {% endif %}
                        {% endfor %}
                    </p>
                    {% else %}
                    <h4 class="header-title-text">
                        {{ song.title }}
                    </h4>
                    {% endif %}
                </div>

                <!-- 添加歌曲至歌單 - 按鈕 -->
                <div class="p-0 col-1 card-header__icon">
                    <button class="song-list-add-btn click-this-to-call-menu" type="button"
                        id="{{ 'callmenu-' + song.sid }}" data-toggle="collapse"
                        data-target="{{ '#listmenu-' + song.sid }}" data-sid="{{ song.sid }}" aria-expanded="false"
                        aria-controls="collapseExample">
                        <i class="fas fa-stream click-this-to-call-menu" data-sid="{{ song.sid }}"></i>
                    </button>
                </div>
            </div>


            <!-- 添加歌曲至歌單 - 選單 -->
            <div class="collapse drop-songlist" id="{{ 'listmenu-' + song.sid }}">
                <div class="add-list-container">
                    <div class="songlist-add">
                        <a class="songlist-add-a" data-toggle="collapse" href="{{ '#songlist-add-' + song.sid }}"
                            role="button" aria-expanded="false" aria-controls="{{ 'songlist-add-' + song.sid }}">
                            <i class="fas fa-plus"></i>
                            <div class="add-song-list-space"></div>
                            新增一份歌單
                        </a>

                        <!-- Add Songlist -->
                        <div class="song-content-container collapse" id="{{'songlist-add-' + song.sid }}">
                            <form class="form-add-songlist" action="{{ url_for('add_songlist_bp.add_songlist') }}"
                                method="POST">
                                <hr class="percent-80">
                                <input type="text" class="d-none" name="posttype" value="withsong">
                                <input type="text" class="d-none" name="song_sid" value="{{ song.sid }}">
                                <input type="text" class="d-none" name="user_id" value="{{ current_user.id }}">
                                <div class="add-list-group">
                                    <p class="text-center">歌單標題</p>
                                    <input type="text" name="title" class="input-addnewlist"
                                        id="{{ 'input-new-list-name-' + song.sid }}" placeholder="輸入新增歌單名稱">
                                </div>
                                <hr class="percent-80">
                                <p class="text-center">隱私設定</p>
                                <div class="add-list-group">
                                    <input class="" type="radio" name="privacy" id="{{ 'check-public-' + song.sid }}"
                                        value="public" checked>
                                    <label class="" for="{{ 'check-public-' + song.sid }}">
                                        <div class="add-song-list-space"></div>
                                        公開
                                    </label>
                                    <small class="form-text text-muted">取得連結的人都可以查看<br>( 如要分享歌單，請選此項 )</small>
                                </div>
                                <div class="add-list-group">
                                    <input class="" type="radio" name="privacy" id="{{ 'check-private-' + song.sid }}"
                                        value="private">
                                    <label class="" for="{{ 'check-private-' + song.sid }}">
                                        <div class="add-song-list-space"></div>
                                        私人
                                    </label>
                                    <small class="form-text text-muted">只有你自己能查看</small>
                                </div>
                                <hr class="percent-80">
                                <button id="{{ 'btn-add-list-' + song.sid }}" type="button"
                                    class="btn-addsonglist btn btn-sm btn-outline-info text-center">新增</button>
                            </form>
                        </div>

                        <!-- End Songlist -->

                    </div>

                    {% if current_user.song_list | length > 0 %}
                    <hr class="my-2">
                    {% endif %}

                    <div class="songlist-list">

                        {% for songlist in current_user.song_list %}

                        {% if not songlist.is_archived %}

                        <form class="form-update-songlist" action="" method="PUT">

                            <input class="songlist_outid d-none" type="text" name="songlist_outid"
                                value="{{ songlist.out_id }}">
                            <input class="song_sid d-none" type="text" name="song_sid" value="{{ song.sid }}">

                            {% if songlist.songs_amount > 0 and song.sid in songlist.songs_sid_list%}

                            <input class="d-none song_in_songlist" type="checkbox" name="song_in_songlist" checked>

                            <button class="dropdown-item song-list-add-check text-success" type="button">
                                <i class="far fa-check-square"></i>
                                <div class="add-song-list-space"></div>
                                {{ songlist.title }}
                            </button>

                            {% else %}

                            <input class="d-none song_in_songlist" type="checkbox" name="song_in_songlist">

                            <button class="dropdown-item song-list-add-check text-secondary" type="button">
                                <i class="far fa-square"></i>
                                <div class="add-song-list-space"></div>
                                {{ songlist.title }}
                            </button>

                            {% endif %}

                        </form>

                        {% endif %}

                        {% endfor %}

                    </div>

                </div>
            </div>
        </h4>
        <div class="card-body">
            <a class="" data-toggle="collapse" href="{{ '#t' + song.sid }}" role="button" aria-expanded="false"
                aria-controls="{{'t' + song.sid }}">
                <div class="card-main-info row pt-2 pb-1">
                    <div class="col-1 col-md-3"></div>
                    <div class="col p-1 align-middle">
                        <span class="song-info">
                            {% if song.language == "Chinese" %}
                            國
                            {% endif %}
                            {% if song.language == "Taiwanese" %}
                            台
                            {% endif %}
                        </span>
                        <span class="song-info">{{ song.num_c }} - {{ song.num_i }}</span>
                    </div>
                    <div class="col-1"></div>
                    <div class="col p-1 align-middle">
                        <span class="song-info">{{ song.tonality }}</span>
                        <span class="song-info">
                            調
                        </span>
                    </div>
                    <div class="col-2 p-1 show-more-song-content">

                        <i class="fas fa-chevron-down"></i>

                    </div>
                    <div class="col-md-1 col-lg-2"></div>
                </div>
            </a>
        </div>
        <div class="song-content-container collapse" id="{{'t' + song.sid }}">
            <div class="card-body pt-0 pb-4 card-body-hide-content card-body-border-bottom">
                <div class="container">
                    <hr>
                </div>
                <div class="row py-3 lyrics-text">
                    <div class="col p-1 text-right"><span>詞：</span><span>{{ song.lyricist }}</span></div>
                    <div class="col-1 p-1"></div>
                    <div class="col p-1 text-left"><span>曲：</span><span>{{ song.composer }}</span></div>
                </div>
                <div class="container lyrics-container">

                    <!-- 歌詞 -->
                    <p class="card-text lyrics-text">
                        {% for i in range(song.lyrics | length) %}
                        {% set s = song.lyrics[i] %}
                        {% if i == 0 %}
                        {% elif (s != "p") and (s != "v") and (s != "c") and (s != "b") and (s != "p\n") and (s != "v\n") and (s != "c\n") and (s != "b\n") %}
                        {{ s }} <br>
                        {% else %}
                        <br>
                        {% endif %}
                        {% endfor %}
                    </p>
                    <!--  -->
                    <div class="pb-2 text-left album-info">
                        <span>
                            詩集：
                        </span>
                        <span>
                            {{ song.album }}
                        </span>
                    </div>

                    <!-- <hr class="song-card-content-hr"> -->

                    <!-- <div class="youtube-player">
                        <iframe width="100%" height="100%" src="https://www.youtube-nocookie.com/embed/LESo18TfBPQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div> -->

                    <hr class="song-card-content-hr">

                    <div class="row pt-3">
                        <div class="col px-3">
                            <a class="ppt-icon"
                                href="{{ url_for('download_ppt_bp.download_ppt', sid=song.sid) + '?next=' + return_url }}">
                                <i class="fas fa-file-powerpoint"></i>
                                <div>投影片</div>
                            </a>
                        </div>
                        <div class="col px-3">
                            <a class="sheet-music-icon"
                                href="{{ url_for('download_sheet_bp.download_sheet', sid=song.sid) + '?next=' + return_url }}">
                                <i class="fas fa-file-alt"></i>
                                <div>歌譜</div>
                            </a>
                        </div>
                        <div class="col px-3">
                            <a class="youtube-icon"
                                href="{{ 'https://www.youtube.com/results?search_query=' + song.title }}">
                                <i class="fab fa-youtube"></i>
                                <div>Youtube</div>
                            </a>
                        </div>
                    </div>

                    <hr class="mt-3 mb-3">
                    <div class="row pt-1">
                        <div class="col px-4">
                            <a class="report-icon"
                                href="{{ url_for('report_bp.report_song', sid=song.sid) + '?next=' + return_url }}">
                                <i class="fas fa-flag"></i>&nbsp;問題回報
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1 col-lg-2"></div>
</div>