caten_music/routes/activate.py
# routes/activate_account.py

from flask import Blueprint, render_template, abort, request, jsonify, flash, redirect, url_for
from jinja2 import TemplateNotFound

from caten_music import helper
from caten_music import models
from caten_music import services

User = models.User

activate_account_bp = Blueprint("activate_account_bp", __name__,
                                template_folder='templates')

resend_activate_mail_bp = Blueprint("resend_activate_mail_bp", __name__,
                                template_folder='templates')

reset_password_bp = Blueprint("reset_password_bp", __name__,
                                template_folder='templates')

ajax_validate_email_bp = Blueprint("ajax_validate_email_bp", __name__,
                                template_folder='templates')


@activate_account_bp.route('/activate/account/check/<gate>/<token>')
def activate_account(gate, token):

    check_result = helper.checkActivateToken(token)

    if check_result:
        if gate == "account_activate":
            user = User.query.filter_by(id=check_result.get("user_id")).first()
            user.is_authenticated = True
            user.is_active = True
            user.save()

            return render_template("activation/active_success.html"), 200
        
        elif gate == "reset_password":
            return redirect(url_for("reset_password_bp.reset_password", step="setting", token=token))

        else:
            flash("錯誤的請求", "danger")
            return redirect("/")

    else:
        return render_template("activation/active_fail.html"), 400

@resend_activate_mail_bp.route('/activate/account/mail/resend', methods=["GET", "POST"])
def resend_activate_mail():

    if request.method == "POST":

        email = request.values.get("email")

        user = User.query.filter_by(email=email).first()

        if user:

            # 取得帳號名稱
            username = user.username

            # 確認 email 是否已經啟動過
            if user.is_authenticated:
                flash("此電子郵件已認證過，請再確認。", "danger")
                return redirect("/activate/account/mail/resend"), 302

            # 產生一個帳號啟動的 token
            token = user.create_activate_token()

            # 啟動 mail 服務
            # 寄出帳號啟動 email
            services.send_mail(sender='Sender@domain.com',
                               recipients=[email],
                               subject='Caten music 帳號註冊認證信',
                               template='activation/verifymail.html',
                               username=username,
                               mail_title="帳號註冊認證信",
                               message="歡迎你, 請點擊下面連結來啟用您的帳號",
                               link_msg="點此啟用您的帳號",
                               link_url=url_for('activate_account_bp.activate_account', gate="account_activate", token=token, _external=True),
                               token=token)

            return render_template("activation/after_register.html", msg_text="啟動信已成功寄出"), 200
        else:
            flash("電子郵件地址錯誤或尚未註冊", "danger")
            return redirect("/activate/account/mail/resend"), 302

    else:
        return render_template("activation/resend_mail.html"), 200


@reset_password_bp.route('/reset/password/<step>/<token>', methods=["GET", "POST"])
def reset_password(step, token):

    if step == "precheck":

        if request.method == "POST":

            email = request.values.get("email")

            user = User.query.filter_by(email=email).first()

            if user:

                # 取得帳號名稱
                username = user.username

                # 產生一個帳號啟動的 token
                token = user.create_activate_token()

                # 啟動 mail 服務
                # 寄出帳號啟動 email
                services.send_mail(sender='Sender@domain.com',
                                recipients=[email],
                                subject='Caten music 密碼重設認證',
                                template='activation/verifymail.html',
                                username=username,
                                mail_title="密碼重設認證",
                                message="您好，請點擊下面連結以重設您的密碼",
                                link_url=url_for('activate_account_bp.activate_account', gate="reset_password", token=token, _external=True),
                                link_msg="點此重設",
                                token=token)

                flash("密碼重設信已經寄出，請前往您的信箱收取信件。", "primary")
                return redirect("/login")
            else:
                flash("電子郵件地址錯誤或尚未註冊", "danger")
                return redirect("/activate/account/mail/resend"), 302

        else:
            return render_template("activation/reset_password.html"), 200
    
    if step == "setting":

        if request.method == "POST":

            # 取得表單資料
            try:
                password = request.values.get("password")
                confirm_password = request.values.get("confirm_password")

                # 後端確認所有資料的格式，雖然前端已經過濾過
                check_result = helper.checkFormat(
                    "checkusername", "check@email.com", "checkdisplayname", password)

            # 當有人故意送出奇怪的request
            except:
                return render_template("error/403.html", error_message="Don't Play With Me."), 400

            # 如果有欄位的資料錯誤，則回傳之前端
            for k, v in check_result.items():
                if not v:
                    return render_template("error/403.html", error_message="Wrong " + k.replace("_check", "")), 400

            # 如果兩次輸入的密碼不一樣
            if not password == confirm_password:
                return render_template("error/403.html", error_message="兩次輸入的密碼不一樣，請再試一次"), 400


            # 以上資料確認完成，重設密碼

            check_result = helper.checkActivateToken(token)

            if check_result:

                user = User.query.filter_by(id=check_result.get("user_id")).first()

                user.reset_pw(password)

                user.update()

                flash("密碼重設成功，請重新登入", "success")
                return redirect("/login")
            
            else:

                flash("錯誤的驗證資訊", "danger")
                return redirect("/login")
        
        else:
            return render_template("account/form_reset_password.html", token=token), 200

    else:
        flash("請求錯誤", "danger")
        return redirect("/")

# 前端 ajax 驗證email
@ajax_validate_email_bp.route("/ajax/validate/email/<email_>", methods=["POST"])
def ajax_validate_email(email_):

    # 如果通過
    result = helper.checkExist().email(email_)

    # 回傳 json
    return jsonify(result)

caten_music/routes/login.py
# routes/login.py

from flask import Blueprint, render_template, abort, jsonify, request, redirect, url_for, flash
from jinja2 import TemplateNotFound
from flask_login import login_user, current_user

import datetime

from caten_music import helper


login_bp = Blueprint("login_bp", __name__,
                    template_folder='templates')

ajax_validate_login_bp = Blueprint("ajax_validate_login_bp", __name__,
                                      template_folder='templates')


@login_bp.route("/login", methods=["GET" ,"POST"])
def login():

    # method == "POST"
    if request.method == "POST":

        # 取得登入表單資料
        try:
            primary = request.values.get("primary")
            password = request.values.get("password")
            next_url = request.values.get("next_url")

            # 後端確認所有資料的格式，雖然前端已經過濾過
            check_result = helper.checkLoginFormat(primary, password)

        # 當有人故意送出奇怪的request
        except Exception as error:
            print(error)
            return render_template("error/403.html", error_message="Don't Play With Me."), 400


        # 如果有欄位的資料錯誤，則回傳之前端
        if check_result["primary_check"] == "failed" or \
            not check_result["password_check"]:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400

        user_to_login = helper.checkLogin(check_result["primary_check"], primary, password)

        if not user_to_login:
            return render_template("error/403.html", error_message="Wrong login imformation."), 400
        
        if not user_to_login.is_authenticated:
            return render_template("activation/account_not_activated.html"), 401
        
        if not user_to_login.is_active:
            flash("此帳號已被凍結，<br>請聯絡管理人員以協助處理，謝謝", "danger")
            return redirect("/")

        # 以上所有註冊資料確認完成，可以註冊帳號
        else:
            login_user(user_to_login, remember=True, duration=datetime.timedelta(weeks=2))

            user_to_login.login_update()

            if next_url == "None":
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect("/"), 302

            if not helper.is_safe_url(next_url):
                return abort(400)
            else:
                flash(user_to_login.displayname + "，歡迎回來" , "success")
                return redirect(next_url), 302

    # method == "GET"
    else:

        if current_user.is_authenticated:
            return redirect("/"), 302

        try:
            return render_template('account/login.html', next_url=request.args.get("next")), 200

        except TemplateNotFound:
            abort(404)


# 前端 ajax 驗證即將登入的表單資料是否通過登入驗證
@ajax_validate_login_bp.route("/ajax/validate/login/<primary_type_>/<primary_>/<password_>", methods=["POST"])
def ajax_validate_login(primary_type_, primary_, password_):

    # 預設為不通過
    result = {"login_pass": False}

    # 如果通過
    if helper.checkLogin(primary_type=primary_type_, primary=primary_, password=password_):
        result["login_pass"] = True

    # 回傳 json
    return jsonify(result)

caten_music/templates/activation/account_not_activated.html
<!-- templates/account_not_activated.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
{%  endblock  %}

{% block title %} - 帳號尚未啟動{% endblock %}

{% block header_title %}
您的帳號尚未啟動
{% endblock %}

{% block header_info %}
<p>很抱歉</p>
<p>請前往你所註冊的電子信箱收取<b>「帳號啟動通知信」</b>，<br>並點選啟動連結來啟動用你的帳號，謝謝！</p>
<p>沒有收到啟動通知信？ <a href="{{ url_for('resend_activate_mail_bp.resend_activate_mail') }}">點這裡重新傳送</a></p>
{% endblock %}

{% block main_hr %}
{% endblock %}

{% block content%}
{% endblock %}

{% block EOF_TAG %}
<!-- EOF templates/account_not_activated.html -->
{% endblock EOF_TAG %}

caten_music/templates/activation/active_fail.html
<!-- templates/active_fail.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
{%  endblock  %}

{% block title %} - 帳號啟動失敗{% endblock %}

{% block header_title %}
帳號啟動失敗
{% endblock %}

{% block header_info %}
<p>啟動驗證碼錯誤或已經失效</p>
<p>原因可能是超過24小時沒有啟動帳號</p>
<p>你可以 <a href="{{ url_for('resend_activate_mail_bp.resend_activate_mail') }}">點這裡重新傳送</a> 驗證碼</p>
{% endblock %}

{% block main_hr %}
{% endblock %}

{% block content%}
{% endblock %}

caten_music/templates/activation/active_success.html
<!-- templates/active_success.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
{%  endblock  %}

{% block title %} - 帳號啟動成功{% endblock %}

{% block header_title %}
感謝你的註冊！
{% endblock %}

{% block header_info %}
<p>帳號已經成功啟動</p>
<p>您要馬上 <a href="{{ url_for('login_bp.login') }}">登入</a> 嗎?</p>
{% endblock %}

{% block main_hr %}
{% endblock %}

{% block content%}
{% endblock %}

caten_music/templates/activation/after_register.html
<!-- templates/after_register.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
{%  endblock  %}

{% block title %} - 還差一步{% endblock %}

{% block header_title %}
還差最後一步
{% endblock %}

{% block header_info %}
<p>{{ msg_text }}</p>
<p>認證碼已經寄送到你所註冊的電子信箱，<br>請前往你的信箱收取，<br>並點選啟動連結來啟動用你的帳號，謝謝！</p>
{% endblock %}

{% block main_hr %}
{% endblock %}

{% block content%}
{% endblock %}

{% block EOF_TAG %}
<!-- EOF templates/after_register.html -->
{% endblock EOF_TAG %}

caten_music/templates/activation/resend_mail.html
<!-- templates/resend_mail.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/account/login.css') }}">
{%  endblock  %}

{% block title %} - 重新取得帳號啟動信{% endblock %}

{% block header_title %}重新傳送帳號啟動信{% endblock %}

{% block content%}

<div class="container container-static">

    <div class="card px-4">
        <form id="form-send" action="{{ url_for('resend_activate_mail_bp.resend_activate_mail') }}" method="POST">

            <!-- email-->
            <div class="form-group mt-4">
                <label for="input-email" class="ml-2">電子郵件地址</label>
                <input name="email" type="text" class="form-control focus-id-1" id="input-email" aria-describedby="emailHelp" autofocus="true">
            </div>

            <input type="text" class="d-none" name="enter-submit-stopper">

            <!-- resend -->
            <button id="btn-send" type="button" class="btn btn-success main-btn">
                重新傳送啟動信
            </button>
        </form>
        <span class="new-to-here"><a class="have-problem" href="#">遇到問題？</a></span>
    </div>
</div>

{% endblock %}

{% block script %}
{{ super () }}
<script src="{{ url_for('static', filename='js/account/resend.js') }}"></script>
{% endblock script %}

caten_music/templates/activation/reset_password.html
<!-- templates/reset_password.html -->

{% extends "base/base.html" %}

{%  block  head  %}
{{  super ()  }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/account/login.css') }}">
{%  endblock  %}

{% block title %} - 重設密碼{% endblock %}

{% block header_title %}
重設密碼
{% endblock %}

{% block header_info %}
<p>很抱歉，為了保護您的隱私，<br>我們無法幫助您找回您的密碼。</p>
<p>請輸入您的電子郵件地址以進行密碼重設。</p>
{% endblock %}

{% block content%}

<div class="container container-static">

    <div class="card px-4">
        <form id="form-send" action="{{ url_for('reset_password_bp.reset_password', step='precheck', token='xyz') }}" method="POST">

            <!-- email-->
            <div class="form-group mt-4">
                <label for="input-email" class="ml-2">電子郵件地址</label>
                <input name="email" type="text" class="form-control focus-id-1" id="input-email" aria-describedby="emailHelp" autofocus="true">
            </div>

            <input type="text" class="d-none" name="enter-submit-stopper">

            <!-- resend -->
            <button id="btn-send" type="button" class="btn btn-success main-btn">
                提交
            </button>
        </form>

        <span class="new-to-here"><a class="have-problem" href="#">遇到問題？</a></span>
    </div>
</div>

{% endblock %}

{% block script %}
{{ super () }}
<script src="{{ url_for('static', filename='js/account/resend.js') }}"></script>
{% endblock script %}

caten_music/templates/activation/verifymail.html
<!-- templates/verifymail.html -->

<!DOCTYPE html>
<html lang="zh-Hant-TW" style="max-width: 700px;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Caten Music {{ mail_title }}</title>
</head>
<body>
    <div class="" style="text-align: center; margin-top: 4rem; width: 80%; margin: auto;">
        <div id="title" style="text-align: center;">
            <h1>Caten Music</h1>
        </div>

        <div class="" style="text-align: center;">
            <h3>{{ username }}, {{ message }}, 謝謝</h3>
            <p style="width: 300px;">
                <a href="{{ link_url }}">
                    {{ link_msg }}
                </a>
            </p>
        </div>
    </div>
</body>
</html>